pyConTextWithaTwist/pyConTextWeb/urls.py
#from pyConTextWeb import settings
import settings
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^pyConTextKit/index/$', 'pyConTextKit.views.index'),
    (r'^pyConTextKit/result/(?P<result_id>\d+)/$', 'pyConTextKit.views.result_detail'),
    (r'^pyConTextKit/report/(?P<reportid>\d+)/$', 'pyConTextKit.views.report_detail'),
    (r'^pyConTextKit/run/$', 'pyConTextKit.views.run'),
    (r'^pyConTextKit/complete/$', 'pyConTextKit.views.complete'),
    (r'^pyConTextKit/itemData_complete/$', 'pyConTextKit.views.itemData_complete'),
    (r'^pyConTextKit/itemData/$', 'pyConTextKit.views.itemData_view'),
    (r'^pyConTextKit/itemData_filter/(?P<cat>\w+)$', 'pyConTextKit.views.itemData_filter'),
    (r'^pyConTextKit/itemData_edit/(?P<itemData_id>\w+)$', 'pyConTextKit.views.itemData_edit'),
    (r'^pyConTextKit/itemData_edit/$', 'pyConTextKit.views.itemData_edit'),
    (r'^pyConTextKit/output_alerts/$', 'pyConTextKit.views.output_alerts'),
    (r'^pyConTextKit/output_results/$', 'pyConTextKit.views.output_results'),
    (r'^pyConTextKit/reports/$', 'pyConTextKit.views.reports'),
    (r'^pyConTextKit/alerts/$', 'pyConTextKit.views.alerts'),
    (r'^pyConTextKit/results/$', 'pyConTextKit.views.results'),
    (r'^pyConTextKit/stats/$', 'pyConTextKit.views.stats'),
    (r'^pyConTextKit/logout/$', 'pyConTextKit.views.logout_view'),
    url(r'^pyConTextKit/ajax_user_search/$', 'pyConTextKit.views.ajax_user_search', name = 'demo_user_search' ),
    (r'^pyConTextKit/report_text/(?P<reportid>\d+)/$', 'pyConTextKit.views.report_text'),
    (r'^pyConTextKit/$', 'pyConTextKit.views.index'),
    (r'^pyConTextKit/admin/', include(admin.site.urls)),
    (r'^pyConTextKit/accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^pyConTextKit/upload_db/(?P<formType>\w+)$', 'pyConTextKit.views.upload_csv'),
    (r'^pyConTextKit/upload_db/$', 'pyConTextKit.views.upload_csv'),
    (r'^pyConTextKit/hide/(?P<idp>\w+)/(?P<idp2>\w+)$', 'pyConTextKit.views.hide'),
    (r'^pyConTextKit/show/(?P<idp>\w+)/(?P<idp2>\w+)$', 'pyConTextKit.views.show'),
    (r'^pyConTextKit/visualize/(?P<idp>\w+)$', 'pyConTextKit.views.resultVisualize'),
    (r'^pyConTextKit/reports_index/', 'pyConTextKit.views.reports_index'),
    (r'^pyConTextKit/annotation_index/', 'pyConTextKit.views.annotation_index')
)
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^pyConTextKit/media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )


pyConTextWithaTwist/pyConTextWeb/pyConTextKit/models.py
#Copyright 2010-2012 Brian E. Chapman, Annie T. Chen, Glenn Dayton IV,
# Rutu Mulkar-Mehta
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.
"""
This module contains the models that are used in the pyConTextKit application.

This application uses the following models:

1) itemDatum: extraction criteria

2) itemDatumSet: a table that stores default extraction criteria settings for
application (e.g. on/off)

3) Report: the reports used by the application

4) Alert: contains a document-level classifications for extracted instances

5) Result: contains each instance identified when Annotate function is run

Note: The get_all_fields method is redundant. A model should be defined for this
application, and then have the other models inherit from it.
"""
from django.db import models
from django.contrib.auth.models import User
import time

# Stores both lexical and Domain data
class Items(models.Model):
    creator = models.ForeignKey(User)
    label = models.CharField(max_length=250)
    category = models.CharField(max_length=250)
    literal = models.CharField(max_length=250)
    re = models.CharField(max_length=250,blank=True)
    re.help_text='<a target="_blank" href="http://www.dhtmlgoodies.com/scripts/regular-expression/regular-expression.html">Regex builder</a>'
    #rule = models.CharField(max_length=250,blank=True)
    RULE_CHOICES = (
        ('forward','Forward'),
        ('backward','Backward'),
        ('terminate','Terminate'),
        ('bidirectional','Bidirectional'),
    )
    rule = models.CharField(max_length=250, choices=RULE_CHOICES, blank=True)
    TYPE_CHOICES = (
    	('domain','Domain'),
    	('linguistic','Linguistic')
    )
    lex_type = models.CharField(max_length=250, choices=TYPE_CHOICES)
    SHOW_CHOICES = (
    	('1','Show'),
    	('0','Hide')
    )
    show = models.CharField(max_length=1, choices=SHOW_CHOICES)
    def __unicode__(self):
        return self.literal

class Report(models.Model):
    dataset = models.CharField(max_length=250)
    reportid = models.TextField()
    report = models.TextField()
    # add label functionality
    def __unicode__(self):
        return str(self.reportid)
    def get_all_fields(self):
        """Returns a list of all field names on the instance."""
        fields = ()
        for f in self._meta.fields:

            fname = f.name
            # resolve picklists/choices, with get_xyz_display() function
            get_choice = 'get_'+fname+'_display'
            if hasattr( self, get_choice):
        	    value = getattr( self, get_choice)()
            else:
                try :
            	    value = getattr(self, fname)
                except User.DoesNotExist:
                    value = None

            # only display fields with values and skip some fields entirely
            if f.editable and value and f.name not in ('id', 'status', 'workshop', 'user', 'complete') :

                fields.append(
                  {
                   'label':f.verbose_name,
                   'name':f.name,
                   'value':value,
                  }
                )
        return fields

# Can we generalize the Alert class to be an application class that is built by
# the user?
class Alert(models.Model):
    reportid = models.IntegerField()
    category = models.TextField()
    alert = models.IntegerField()
    report = models.TextField()
    def __unicode__(self):
        return str(self.reportid)
    def get_all_fields(self):
        """Returns a list of all field names on the instance."""
        fields = ()
        for f in self._meta.fields:

            fname = f.name
            # resolve picklists/choices, with get_xyz_display() function
            get_choice = 'get_'+fname+'_display'
            if hasattr( self, get_choice):
                value = getattr( self, get_choice)()
            else:
                try :
                    value = getattr(self, fname)
                except User.DoesNotExist:
                    value = None

            # only display fields with values and skip some fields entirely
            if f.editable and value and f.name not in ('id', 'status', 'workshop', 'user', 'complete') :

                fields.append(
                  {
                   'label':f.verbose_name,
                   'name':f.name,
                   'value':value,
                  }
                )
        return fields

# Don't know that we want to store this back into the database
# How would we make results general?
class Result(models.Model):
    label = models.CharField(max_length=250)
    date = models.CharField(max_length=35)
    path = models.CharField(max_length=1000)
    #Do we want to store information about what domain and lexical were used?

    def __unicode__(self):
	    return str(self.reportid)

pyConTextWithaTwist/pyConTextWeb/pyConTextKit/forms.py
#Copyright 2010 Annie T. Chen
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.
"""
This module contains the forms that are used in the pyConTextKit application.
"""
from django import forms
from django.forms import ModelForm
from django.forms.widgets import RadioSelect, CheckboxSelectMultiple
from django.utils.safestring import mark_safe
"""
	**TODO**
		Eventually remove import of itemDatum
"""
from pyConTextKit.models import Report, Items

class HorizRadioRenderer(forms.RadioSelect.renderer):
    """ this overrides widget method to put radio buttons horizontally
        instead of vertically.
    """
    def render(self):
            """Outputs radios"""
            return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))

UNCERTAINTY_CHOICES = (('separate_uncertainty','distinguish certainty from uncertainty'), ('allow_uncertainty','do not distinguish certainty from uncertainty'), ('no_uncertainty','do not include instances of uncertainty'))

class SearchForm(forms.Form):
    """
    A form that takes the input for a simple search.
    """
    term = forms.CharField(label = 'Search term', required=False)

class RunForm(forms.Form):
    """
    This form enables the user to specify settings for Annotate (formerly called "Analyze").
    """
    outputLabel = forms.CharField(max_length=150,label='Output Label')
    dataset = forms.ChoiceField(label = 'Report dataset', choices=[], required=False)
    #category = forms.CharField(label = 'Target category', required=False)
    #limit = forms.IntegerField(required=False)
    label = forms.ChoiceField(label = 'Label of linguistic', choices=[], required=False)
    labelDomain = forms.ChoiceField(label = 'Label of domain', choices=[], required=False)
    def __init__(self, *args, **kwargs):
        super(RunForm, self).__init__(*args, **kwargs)
        self.fields['dataset'].choices = Report.objects.all().values_list("dataset","dataset").distinct()
        self.fields['label'].choices = Items.objects.all().filter(lex_type='linguistic').values_list("label","label").distinct()
        self.fields['labelDomain'].choices = Items.objects.all().filter(lex_type='domain').values_list("label","label").distinct()

class DocClassForm(forms.Form):
    """
    This form accepts user input for classifying documents.
    """
    limit_pos = forms.BooleanField(label="Positive Findings Only", required=False,initial=True)
    limit_new = forms.BooleanField(label="New Findings Only", required=False,initial=True)
    uncertainty = forms.ChoiceField(widget=forms.RadioSelect, choices=UNCERTAINTY_CHOICES,initial={'separate_uncertainty','separate_uncertainty'})
    def __init__(self, *args, **kwargs):
        super(DocClassForm, self).__init__(*args, **kwargs)

"""
	UPDATED 7/27/12 G.D.
	Changed model from itemDatum to Lexical
"""
class itemForm(forms.ModelForm):
    """
    This form for the Lexical class employs the default ModelForm.
    """
    CHOICES = (
    	('domain','Domain'),
    	('linguistic','Linguistic')
    )
    lex_type = forms.ChoiceField(label="Lexicon Type",choices=CHOICES, widget=forms.RadioSelect(renderer=HorizRadioRenderer))
    label = forms.CharField(label="Name")
    class Meta:
        model = Items
        exclude = ('show',)

class ReportForm(forms.Form):
    """
    This form enables the user to select a report to view.
    """
    REPORT_CHOICES = [(i.id, i.id) for i in Report.objects.all()]
    REPORT_CHOICES.insert(0, ('', '-- choose a report number first --'))

    id = forms.ChoiceField(choices=REPORT_CHOICES, widget=forms.Select(attrs={'onchange':'get_report_number();'}))
    text = forms.CharField()

class EditReport(forms.ModelForm):

	class Meta:
		report = Report

"""
class UploadDatabase(forms.Form):
	label = forms.CharField(max_length=250)
	csvfile  = forms.FileField()
"""

class UploadDatabaseReports(forms.Form):
    dataset = forms.CharField(max_length=250, required=True)
    csvfile  = forms.FileField(label="CSV File", required=True)

class UploadDatabaseLexicon(forms.Form):
    label = forms.CharField(label="Name",max_length=250, required=True)
    csvfile  = forms.FileField(label="CSV File", required=True)
    CHOICES = (
    	('domain','Domain'),
    	('linguistic','Linguistic')
    )
    like = forms.ChoiceField(label="Lexicon Type",choices=CHOICES, widget=forms.RadioSelect())

pyConTextWithaTwist/pyConTextWeb/templates/pyConTextKit/alerts.html
{% extends "base.html" %}

{% block pagetitle %}Annotation Results{% endblock %}
{% block content %}
        
<p>These are the annotation results. You can also <a href="/pyConTextKit/output_alerts/">output them to a CSV file</a>.
{% for j in alert.all %}
<p>{% for f in j.get_all_fields %}
{{f.label}}:{{f.value}}<br>
{% endfor %}
{% endfor %}

      
{% for i in alert.all %}
{% if forloop.first %}
<table>
<tr>
<th>reportid</th>
<th>category</th>
{% if i.disease %}
<th>disease</th>
{% endif %}
{% if i.uncertainty %}
<th>uncertainty</th>
{% endif %}
{% if i.historical %}
<th>historical</th>
{% endif %}
</tr>
{% endif %}
<tr class="{% if forloop.counter|divisibleby:2 %}even{% else %}odd{% endif %}">
<td><a href="/pyConTextKit/report/{{i.reportid}}/">{{ i.reportid }}</a></td>
<td>{{ i.category }}</td>
{% if i.disease %}
<td>{{ i.disease }}</td>
{% endif %}
{% if i.uncertainty %}
<td>{{ i.uncertainty }}</td>
{% endif %}
{% if i.historical %}
<td>{{ i.historical }}</td>
{% endif %}
</tr>
{% endfor %}
</table>

{% endblock %}

pyConTextWithaTwist/pyConTextWeb/templates/pyConTextKit/edit_report.html
{% extends "base.html" %}

{% block title %}pyConTextKit{% endblock %}

{% block pagetitle %}Edit Extraction Criterion{% endblock %}
{% block content %}

<h2>Edit Report</h2>

<form action="" method="post">
{% csrf_token %}
<table>
{{ form }}
</table>
<input type="submit" value="Submit" />
</form>

{% endblock %}

pyConTextWithaTwist/pyConTextWeb/templates/pyConTextKit/item_view.html
<form action="." method="post" accept-charset="utf-8">
    <table>
        <thead>
            <tr>
                <th>include</th>
                <th>literal</th>
                <th>re</th>
            </tr>
        </thead>
        <tbody>
        {% for form in formset.forms %}
            <tr>
                <td>
                    {# don't forget about the id field #}
                    {{ form.id }}
                    {{ form.include }}
                </td>
                <td>{{ form.literal }}</td>
                <td>{{ form.re }}</td>
            </tr>
        {% endfor %}        
        </tbody>
    </table>
    <p>
        {# and don't forget about the management form #}
        {{ formset.management_form }}
        <button type="submit" name="action" value="save">{% chunk "save" %}</button>
        <button type="submit" name="action" value="delete">{% chunk "delete" %}</button>
    </p>
</form>

pyConTextWithaTwist/pyConTextWeb/templates/pyConTextKit/itemdata.html
{% extends "base.html" %}

{% block pagetitle %}Add/Edit lexical item{% endblock %}

{% block content %}
<p>Below you will find all of the annotation criteria in the lexicon.  Here you
are able to do the following:
<ul>
<li><a href="/pyConTextKit/itemData_edit/">add a new item</a></li>
<li>edit an existing item by clicking on it's literal</li>
</ul>

<p>You can also view a subset of the lexicon by clicking on its category name:

<p span class="itemdata_categories">
<table>
	<tr>
		<th>Domain Lexicon Label (Targets)</th>
	</tr>
	<tr>
		<td><input type="checkbox" checked/>{{ domain|safe }}</td>
	</tr>
</table>
<!--<a href="/pyConTextKit/itemData_filter/CRITICAL_CONCEPTS">Critical Concepts</a>,
<a href="/pyConTextKit/itemData_filter/SO">Surveillance Ontology</a><br>-->
<table>
	<tr>
		<th>Linguistic Lexicon Label (Modifiers)</th>
	</tr>
	<tr>
		<td><input type="checkbox" checked/>{{ linguistic|safe }}</td>
	</tr>
</table>
<!--<a href="/pyConTextKit/itemData_filter/CONJ">Conjugates</a>,
<a href="/pyConTextKit/itemData_filter/DEFINITE_EXISTENCE">Definite Existence</a>,
<a href="/pyConTextKit/itemData_filter/DEFINITE_NEGATED_EXISTENCE">Definite Negated
Existence</a>,
<a href="/pyConTextKit/itemData_filter/FUTURE">Future</a>,<br />
<a href="/pyConTextKit/itemData_filter/INDICATION">Indication</a>,
<a href="/pyConTextKit/itemData_filter/PROBABLE_EXISTENCE">Probable Existence</a>,
<a href="/pyConTextKit/itemData_filter/PROBABLE_NEGATED_EXISTENCE">Probable Negated
Existence</a>,
<a href="/pyConTextKit/itemData_filter/PSEUDONEG">Pseudo-Negated</a>-->
</span>

<form action="/pyConTextKit/itemData/" method="post">
{% csrf_token %}
<span style="width:40px; height:20px; background-color:#0BB5FF; color:white; font-size:10px;">DOM</span> = Domain <span style="width:40px; height:20px; background-color:#98FB98; font-size:10px;">LNG</span> = Linguistic |
Search for an existing term: {{ form.term }}
<input type="submit" value="Search" /> | <a href="/pyConTextKit/show/showall">Select All</a> &middot; <a href="/pyConTextKit/show/hideall">Hide All</a>
</form>

<form action="/pyConTextKit/itemData/" method="post">
{% csrf_token %}
{{ formset.management_form }}
<table width="710">
<tr>
<th></th>
<th>category</th>
<th>literal</th>
<th>lexicon name</th>
<th></th>
</tr>
{% for f in formset.forms %}
<tr class="{% if forloop.counter|divisibleby:2 %}even{% else %}odd{% endif %}" style="{% ifequal f.instance.show '0' %} opacity:.6 {% endifequal %}">
	<td>
	{% ifequal f.instance.lex_type "domain" %}
			<span style="width:40px; height:20px; background-color:#0BB5FF; color:white; font-size:10px;">DOM</span>
	{% endifequal %}
	{% ifequal f.instance.lex_type "linguistic" %}
		<span style="width:40px; height:20px; background-color:#98FB98; font-size:10px;">LNG</span>
	{% endifequal %}
	</td>
    <td>{{ f.id }}{{ f.instance.category }}</td>
    <td><a name="{{ forloop.counter }}" href='/pyConTextKit/itemData_edit/{{f.instance.id}}'>{{ f.instance.literal }}</a></td>
    <td>{{ f.instance.label }}</td>
    {% ifequal f.instance.show "1" %}
    	<td><a style="border:no-style;" href="/pyConTextKit/hide/{{ f.instance.id }}/{{ forloop.counter }}"><img style="margin-top:2px;" width="13" height="13" title="Hide" src="{{ MEDIA_URL }}/add.png" /></a></td>
	{% endifequal %}
	{% ifequal f.instance.show "0" %}
		<td><a style="border:no-style;" href="/pyConTextKit/show/{{ f.instance.id }}/{{ forloop.counter }}"><img style="margin-top:2px;" width="13" height="13" title="Show" src="{{ MEDIA_URL }}/close2.png" /></a></td>
	{% endifequal %}
</tr>
{% endfor %}
</table>
</form>

{% endblock %}

pyConTextWithaTwist/pyConTextWeb/templates/pyConTextKit/itemdata_complete.html
{% extends "base.html" %}

{% block content %}

<p>All done.  Have a good day!

<p><a href="/pyConTextKit/itemData_edit/">Add another</a>

{% endblock %}

pyConTextWithaTwist/pyConTextWeb/templates/pyConTextKit/itemdata_edit.html
{% extends "base.html" %}

{% block extra_js %}
<script type="text/javascript">
$( document ).ready( function() {
	$( '#searchSubmit' ).click( function() {
		q = $( '#q' ).val();
		$( '#results' ).html( '&nbsp;' ).load( '{% url demo_user_search %}?q=' + q );
	});
});

$( document ).ajaxStart( function() {
	$( '#spinner' ).show();
}).ajaxStop( function() {
	$( '#spinner' ).hide();
});
</script>
{% endblock %}

{% block title %}pyConTextKit{% endblock %}

{% block pagetitle %}Edit Extraction Criterion{% endblock %}
{% block content %}

<p><span font-size=11>{{ intro|safe }}</span>

<style type="text/css">
#id_label,#id_category,#id_literal{
	width:250px;
}
</style>

<form action="" method="post">
{% csrf_token %}

<div style="width:40%;">
{{ dup|safe }}
</div>

<table border="0">
<tr>
	<td>
		<table class="wide">
		{{ form }}
		</table>
	</td>
	<td valign="top">
		<script type='text/javascript'>
		function passCat(){
			var info = $("#category-items").val();
			$("#id_category").val(info);
		}
		</script>
		<div style='margin-top:58px;'>
			OR <select id='category-items'>
				<option value='---'>---</option>
			{% for index in cat_items %}
				<option value="{{ index }}">{{ index }}</option>
			{% endfor %}
			</select>
			<input type='button' id='add-cat' value='&laquo; Add Category' onclick='passCat()' />
		</div>
		<br />Example entry<hr />
		<pre style="margin-top:-25px;">
		<table border="0" style="background-color:#FFFACD; padding:5px;">
			<tr><td align="right"><b>Creator</b></td><td>Joe Example</td></tr>
			<tr><td align="right"><b>Name</b></td><td>Domain Items 2012</td></tr>
			<tr><td align="right"><b>Category</b></td><td>PULMONARY_EMBOLISM</td></tr>
			<tr><td align="right"><b>Re</b></td><td>\bpe\b</td></tr>
			<tr><td align="right"><b>Rule</b></td><td></td></tr>
			<tr><td align="right"><b>Lexicon Type</b></td><td>Domain</td></tr>
		</table>
		</pre>
	</td>
</tr>
</table>
<input type="submit" name="submit" value="Submit" />
</form>

<div>

<!--
<p>Search for a sample report:
<p>Report ID: <input id="q" type="text"/>
<input id="searchSubmit" type="submit" value="Search"/>
<br/>
<div class="margin">
<span id="spinner"><img src="{{ MEDIA_URL }}spinner.gif"/></span>
</div>
-->
</div>

<div id="results"></div>

{% endblock %}

pyConTextWithaTwist/pyConTextWeb/templates/pyConTextKit/report_detail.html
{% extends "base.html" %}

{% block pagetitle %}Report Detail{% endblock %}

{% block content %}

<table>        
{% for f in report.get_all_fields %}
<tr>
<th>{{f.label}}</th>
<td>{{f.value}}</td>
</tr>
{% endfor %}
</table>
{% endblock %}

pyConTextWithaTwist/pyConTextWeb/templates/pyConTextKit/report_form.html
{% extends "base.html" %}
{% block head %}
<script type="text/javascript" src="/media/prototype.js"></script>
<script type="text/javascript" src="/media/my_ajax_function.js"></script>
{% endblock %}

{% block content %}
    {% if form_was_valid %}
        {# ... show whatever... #}
    {% else %}
        <form action="/auto/reserve/" method="POST">
        <ul>
        {{ form.as_ul}}
        <li><label for="submit">&nbsp;</label>
        <input type="submit" id="submit" name="submit" value="Submit"/></li>
        </ul>
        </form>
    {% endif %}
{% endblock %}

pyConTextWithaTwist/pyConTextWeb/templates/pyConTextKit/report_test.html
<p>Sample report:
<table>
<tr>
<th>id</th><td>{{ results.id }}</td>
</tr>
<tr>
<th>dataset</th><td>{{ results.dataset }}</td>
</tr>
<tr>
<th>reportid</th><td>{{ results.reportid }}</td>
</tr>
<tr>
<th>reportType</th><td>{{ results.reportType }}</td>
</tr>
<tr>
<th>report</th><td>{{ results.report }}</td>
</tr>
</table>

pyConTextWithaTwist/pyConTextWeb/templates/pyConTextKit/reports.html
{% extends "base.html" %}

{% block pagetitle %}Reports{% endblock %}

{% block content %}

<p>These are the reports.

{% if report %}

<table>
{% for r in report.object_list %}
<tr>
<td>
<table>
<tr>
<th>id</th><td>{{ r.id }}</td>
</tr>
<tr>
<th>dataset</th><td>{{ r.dataset }}</td>
</tr>
<tr>
<th>reportid</th><td>{{ r.reportid }}</td>
</tr>
<tr>
<th>report type</th><td>{{ r.reportType }}</td>
</tr>
<tr>
<th>report</th><td>{{ r.report }}</td>
</tr>
</table>
</td>
</tr>
{% endfor %}
</table>
{% endif %}

<div class="paging">
<table align="center">
<tr>
<td>
{% if report.has_previous %}
<a href="?page={{ report.previous_page_number}}" style="text-decoration:none;color:#000000;" ><img src="/static/images/article_previous.gif" border="0"/>&nbsp;&nbsp;prev&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;</a>
{% endif %}
</td>
<td>
Page {{ report.number }} of {{ report.paginator.num_pages }}
</td>
<td>
{% if report.has_next %}
<a href="?page={{ report.next_page_number }}" style="text-decoration:none;color:#000000;">&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;next&nbsp;&nbsp;<img src="/static/images/article_next.gif" border="0"/></a>{% endif %}
</tr>
</table></div>

{% endblock %}

pyConTextWithaTwist/pyConTextWeb/templates/pyConTextKit/result_detail.html
{% extends "base.html" %}

{% block content %}
        
<p>Analysis Results

<p>These are the results.

<p>{% for f in result.get_all_fields %}
{{f.label}}:{{f.value}}<br>
{% endfor %}

{% endblock %}

pyConTextWithaTwist/pyConTextWeb/templates/pyConTextKit/results.html
{% extends "base.html" %}

{% block pagetitle %}Analysis Results{% endblock %}

{% block content %}

<p>These are the results. You can also <a href="/pyConTextKit/output_results/">output them to a CSV file</a>.

<table>
<tr>
<th>id</th>
<th>name</th>
<th>path</th>
<th>date</th>
</tr>
</tr>
{% for i in result.all %}
<tr class="{% if forloop.counter|divisibleby:2 %}even{% else %}odd{% endif %}">
<td>{{ i.id }}</td>
<td><a href="/pyConTextKit/visualize/{{ i.id }}">{{ i.label }}</a></td>
<td>{{ i.path }}</td>
<td>{{ i.date }}</td>
</tr>
{% endfor %}
</table>
<div id="chart"></div>
<script type="text/javasript" src="http://www.drewconway.com/zia/wp-content/uploads/2011/07/mikedewar/mikedewar.js"></script>
{% endblock %}